name: Composite java action
description: Setup JDK and maven
inputs:
  distribution:
    description: Which JDK to use
    default: temurin
  java-version:
    description: Major version of JDK
    required: true
  maven-version:
    description: Version of Maven to use
    required: true
    default: 3.9.2
  overwrite-settings:
    description: Overwrite settings.xml
    required: false
    default: false
  cache:
    description: Cache java artifacts
    required: false
    default: false

runs:
  using: "composite"
  steps:
  - name: Setup java
    if: ${{ inputs.cache }}
    uses: actions/setup-java@v4.0.0
    with:
      distribution: ${{ inputs.distribution }}
      overwrite-settings: ${{ inputs.overwrite-settings }}
      java-version: ${{ inputs.java-version }}
      cache: ${{ inputs.cache == 'true' && 'maven' || '' }}

  - name: Set up Maven
    uses: stCarolas/setup-maven@v5
    with:
      maven-version: ${{ inputs.maven-version }}
